### ISSUE TITLE
Add support for nestjs/config

### ISSUE THREAD

**Issue by pzamzow** [team-supercharge/nest-amqp#10]
It would be helpful if the module would support the [nestjs/config](https://github.com/nestjs/config) module. A lot of other standard NestJS modules provide a `forRootAsync` function, which can be used for exactly this purpose. Here some examples:

- [Mongoose Module](https://docs.nestjs.com/techniques/mongodb#async-configuration)
- [Typeorm Module](https://docs.nestjs.com/techniques/database#async-configuration)

It would require the parameters `inject`, `useFactory` and `imports`. The result of the factory function should be used to create the AMQP connection.

**Comment by tahubu** [comment]
Version `2.0.0` already supports this feature.
