### ISSUE TITLE
Authentication Failed when username or password contain special characters.

### ISSUE THREAD

**Issue by jmargieh** [team-supercharge/nest-amqp#24]
An example of failed authentication would be like this:

```QueueModule.forRoot('amqps://someUserName:somePasswordWithSpecialCharsLike=$!-@localhost:7027')```

Thanks,
Jawad

**Comment by jmargieh** [comment]
@tahubu - Can you please have a look at this https://github.com/team-supercharge/nest-amqp/pull/25

Regards,
Jawad

**Comment by tahubu** [comment]
Hi @jmargieh ,

thank you for reporting this issue. It is fixed in `v2.0.1`.

Best regard,
Tamás
