### ISSUE TITLE
no support for filters in listener

### ISSUE THREAD

**Issue by solidhtp** [team-supercharge/nest-amqp#49]
Hello,

ActiveMQ supports filters by `JMS selector expressions` or `XPath`. [`rhea`](https://github.com/amqp/rhea/) supports message filtering as described [here](https://github.com/amqp/rhea/blob/main/examples/selector/recv.js#L44).
`@Listen` accepts only `string` type in source.
``` typescript
@Listen(source: string, options: ListenOptions)
```
In order to support filters `source` should be type of `string | Source` [Source as described in this line](https://github.com/amqp/rhea/blob/main/examples/selector/recv.js#L44). I tried it locally with type `Source` and filters were working fine.

I can create a PR which simply changes the source type from `string` to `string | Source`.

**Comment by raschan** [comment]
Hi @solidhtp ,

Awesome, a PR would be welcomed.

**Comment by solidhtp** [comment]
@raschan PR created. Please merge.

**Comment by raschan** [comment]
Hi @solidhtp 

Sorry for the delay, life happened....

I've updated the package with support for the `Source` object defined in `rhea-promise`
