### ISSUE TITLE
Failover scenario not supported

### ISSUE THREAD

**Issue by pzamzow** [team-supercharge/nest-amqp#5]
Hi,

first thanks for this great NestJS module. 

I tried to use it in one of my projects to connect to Azure service bus and Amazon MQ. On Amazon I have an active/standby setup. This means multiple servers are running, but the connection to just one of them is possible at a time. The other will refuse the connection. 
As by the comment given in [amqp/rhea/issues#124](https://github.com/amqp/rhea/issues/124#issuecomment-426588861), I need to use the `connection_details` function to support this. This did not worked for me, when using this module, because the [client factory](https://github.com/team-supercharge/nest-amqp/blob/master/src/queue.module.ts#L25) throws an error on the first connection attempt to the not active server. After that no attempt to the second (active) server is triggered.

I could solve this issue by adding a try/catch to your factory function, but it would be nice, if this would be supported by the module itself.

**Comment by tahubu** [comment]
Hi @pzamzow 

thank you for your feedback. In version `1.1.0` we added a new connection option called `throwExceptionOnConnectionError` which value is `false` by default. I think this option with `false` can solve your problem.

**Comment by pzamzow** [comment]
@tahubu thanks a lot for this enhancement. I implemented it and it is working as expected.
