### ISSUE TITLE
Support for HTTPS Transports

### ISSUE THREAD

**Issue by yanna92yar** [team-supercharge/nest-amqp#64]
Hi,
I know this library supports only amqp protocol, is it in the scope of this library to support [HTTPS Transports](https://activemq.apache.org/http-and-https-transports-reference) AMQP over HTTP? 

Sorry I'm making many assumptions as I'm new to message brokers. Correct me if I'm wrong.

The error trying to connect to `https://url` is simply:

>  Not supported connection protocol: https:

**Comment by raschan** [comment]
hi @yanna92yar,

What is it that you are trying to achive? Perhaps try using `amqps://url` instead of https. In the end, the protocol will be translated to either `tcp`, `tls` or `ssl` as used by [rhea](https://github.com/amqp/rhea).

**Comment by yanna92yar** [comment]
ok thanks a lot. I will try looking at rhea options.
