### ISSUE TITLE
Identifying which user is publishing

### ISSUE THREAD

**Issue by amangeot** [team-supercharge/nest-amqp#68]
Hello,
We have a queue which multiple users can use to publish some messages. We would like to apply some kind of authorization by identifing which user published the message we received in a listener.

How would you access message headers for ActiveMQ for example if user was accessible there?

Another road we are looking at is having 1 queue per user but then what would be the best way to have 1 listener per queue without having to hard code a queue source for each user?

Thank you very much for this library

**Comment by amangeot** [comment]
Ah that would be awesome.

What do you mean with "spin up a new instance for each user"?

We though about having a dynamic module read some config and instantiate one module per user using a module factory so that we can pass the queue string to the @Listen for each user / module.

Do you have another suggestion?

**Comment by raschan** [comment]
I'm making headway with this (adding metadata as a 3rd parameter to the callback), hopefully will be finished by tomorrow. I'm just having some issues with the unit tests

**Comment by raschan** [comment]
see: https://github.com/team-supercharge/nest-amqp/pull/69

**Comment by amangeot** [comment]
Ah great, thank you @raschan for your reactivity! 🔥

Do you manage to read which user published a message using metadata?
