### ISSUE TITLE
Is it safe to override listener callback ?

### ISSUE THREAD

**Issue by yanna92yar** [team-supercharge/nest-amqp#70]
Hi,
I want to be able to completely stop from listening to a queue if this is possible, otherwise if this is not possible, would it be fine to register a new empty (for example) callback on the same queue ?

Like to unregisted a queue I would put

```ts
queueService.listen('queue_1', (message, control) =>  {}, options)
```

Thank you in advance.

**Comment by raschan** [comment]
Hi @yanna92yar !

If I understand correctly, you want to register listeners during runtime?

That use case is currently not really supported by us.
Override at the moment is also not supported, but that could be a quick change.

**Comment by yanna92yar** [comment]
Hi @raschan 
Thank you so much for the response !

Yes at runtime; We have been using `queueService.listen` without any problems.

Could you confirm please that passing a new callback (empty in this case) would simply override the old one ?

Thanks !

**Comment by yanna92yar** [comment]
nothing special about the callback (if you mean my implementation ?), it is isolated and just run a simple function on `message`.
So my initial need is not really to replace it, just to *unlisten* from a queue.

**Comment by raschan** [comment]
As I said, sadly, that is not supported at the moment. I'll see what can I come up with in the weekend, and get back to you

**Comment by raschan** [comment]
@yanna92yar added a `removeListener` function on the `QueueService`, should work as expected

**Comment by yanna92yar** [comment]
Thank you so much, I appreciate your responsiveness !
Kindly
